package com.example.demo01.Demo;

public class mapper {

    public static BookDTO maptoBookDTO(BookEntity bookEntity){
        return  new BookDTO(

                bookEntity.getAuthor(),
                bookEntity.getPublisher()
        );
    }

    public static BookEntity maptoBookEntity(BookDTO bookDTO){
        return new BookEntity(
                0L, // id will be generated by the database
                bookDTO.getAuthor(),
                bookDTO.getPublisher()

        );
    }
}
